"""Simulation tools for Othello Bot Arena."""

from sim.experiment import (
    ExperimentBotSummary,
    ExperimentResult,
    aggregate_experiment_runs,
    experiment_to_dict,
    render_experiment_report,
    run_experiment,
    summarize_experiment_runs,
    write_experiment_json,
)
from sim.export import (
    matches_rows,
    standings_rows,
    tournament_to_dict,
    write_matches_csv,
    write_standings_csv,
    write_tournament_json,
)
from sim.presets import PRESET_ROSTERS, resolve_roster
from sim.tournament import (
    BotEntry,
    BotStats,
    MatchResult,
    MatchupStats,
    TournamentResult,
    build_entries,
    main,
    render_tournament_report,
    run_match,
    run_round_robin,
    summarize_matchups,
    summarize_tournament,
)

__all__ = [
    "BotEntry",
    "BotStats",
    "ExperimentBotSummary",
    "ExperimentResult",
    "MatchResult",
    "MatchupStats",
    "PRESET_ROSTERS",
    "TournamentResult",
    "aggregate_experiment_runs",
    "build_entries",
    "experiment_to_dict",
    "main",
    "matches_rows",
    "render_tournament_report",
    "render_experiment_report",
    "resolve_roster",
    "run_match",
    "run_round_robin",
    "run_experiment",
    "standings_rows",
    "summarize_experiment_runs",
    "summarize_matchups",
    "summarize_tournament",
    "tournament_to_dict",
    "write_experiment_json",
    "write_matches_csv",
    "write_standings_csv",
    "write_tournament_json",
]
